
import type { Module } from './types';

export const COURSE_OUTLINE: Module[] = [
    {
        id: 'm1',
        title: 'Module 1: 5G Security Fundamentals',
        topics: [
            { id: 'm1t1', title: 'Evolution of Mobile Network Security (2G to 5G)' },
            { id: 'm1t2', title: '5G Security Architecture Overview' },
            { id: 'm1t3', title: 'Key Security Principles in 5G Networks' },
            { id: 'm1t4', title: '3GPP Security Standards and Specifications' },
            { id: 'm1t5', title: 'Security Domains: Access, Transport, and Core' },
            { id: 'm1t6', title: '5G Trust Model and Security Boundaries' },
        ],
    },
    {
        id: 'm2',
        title: 'Module 2: 5G Network Architecture Security',
        topics: [
            { id: 'm2t1', title: 'Service-Based Architecture (SBA) Security' },
            { id: 'm2t2', title: 'Network Function Virtualization (NFV) Security' },
            { id: 'm2t3', title: 'Software-Defined Networking (SDN) Security' },
            { id: 'm2t4', title: 'Network Slicing Security Mechanisms' },
            { id: 'm2t5', title: 'Edge Computing (MEC) Security Challenges' },
            { id: 'm2t6', title: 'Cloud-Native 5G Core Security' },
        ],
    },
    {
        id: 'm3',
        title: 'Module 3: Authentication and Key Management',
        topics: [
            { id: 'm3t1', title: '5G-AKA (Authentication and Key Agreement)' },
            { id: 'm3t2', title: 'EAP-AKA Prime Protocol Deep Dive' },
            { id: 'm3t3', title: 'SUPI/SUCI and Subscriber Privacy' },
            { id: 'm3t4', title: 'Key Derivation and Hierarchy in 5G' },
            { id: 'm3t5', title: 'Secondary Authentication Mechanisms' },
            { id: 'm3t6', title: 'AUSF, ARPF, and SIDF Functions' },
        ],
    },
    {
        id: 'm4',
        title: 'Module 4: Radio Access Network (RAN) Security',
        topics: [
            { id: 'm4t1', title: 'gNodeB Security Architecture' },
            { id: 'm4t2', title: 'Air Interface (NR) Security Mechanisms' },
            { id: 'm4t3', title: 'RRC and UP Ciphering and Integrity' },
            { id: 'm4t4', title: 'Open RAN (O-RAN) Security Considerations' },
            { id: 'm4t5', title: 'Xn and NG Interface Security' },
            { id: 'm4t6', title: 'Beam Security and Physical Layer Attacks' },
        ],
    },
    {
        id: 'm5',
        title: 'Module 5: Core Network Security',
        topics: [
            { id: 'm5t1', title: 'AMF Security Functions' },
            { id: 'm5t2', title: 'SMF and UPF Security Mechanisms' },
            { id: 'm5t3', title: 'UDM/UDR Data Protection' },
            { id: 'm5t4', title: 'NRF and Service Discovery Security' },
            { id: 'm5t5', title: 'PCF Policy Enforcement Security' },
            { id: 'm5t6', title: 'NSSF Network Slice Security' },
        ],
    },
    {
        id: 'm6',
        title: 'Module 6: Encryption and Cryptography',
        topics: [
            { id: 'm6t1', title: '5G Encryption Algorithms (NEA1, NEA2, NEA3)' },
            { id: 'm6t2', title: 'Integrity Algorithms (NIA1, NIA2, NIA3)' },
            { id: 'm6t3', title: '256-bit Key Support in 5G' },
            { id: 'm6t4', title: 'TLS 1.3 for Service-Based Interfaces' },
            { id: 'm6t5', title: 'IPsec for Transport Security' },
            { id: 'm6t6', title: 'Post-Quantum Cryptography Preparation' },
        ],
    },
    {
        id: 'm7',
        title: 'Module 7: User Privacy Protection',
        topics: [
            { id: 'm7t1', title: 'IMSI Catchers and Historical Vulnerabilities' },
            { id: 'm7t2', title: 'SUPI Concealment with SUCI' },
            { id: 'm7t3', title: 'Home Network Public Key Infrastructure' },
            { id: 'm7t4', title: 'ECIES Encryption for Identity Protection' },
            { id: 'm7t5', title: 'Location Privacy Enhancements' },
            { id: 'm7t6', title: 'Tracking Prevention Mechanisms' },
        ],
    },
    {
        id: 'm8',
        title: 'Module 8: Network Slicing Security',
        topics: [
            { id: 'm8t1', title: 'Slice Isolation Principles and Mechanisms' },
            { id: 'm8t2', title: 'S-NSSAI Security Considerations' },
            { id: 'm8t3', title: 'Cross-Slice Attack Vectors' },
            { id: 'm8t4', title: 'Slice-Specific Authentication' },
            { id: 'm8t5', title: 'Resource Isolation and QoS Security' },
            { id: 'm8t6', title: 'Slice SLA Security Monitoring' },
        ],
    },
    {
        id: 'm9',
        title: 'Module 9: Roaming and Interconnection Security',
        topics: [
            { id: 'm9t1', title: 'SEPP (Security Edge Protection Proxy)' },
            { id: 'm9t2', title: 'N32 Interface Security' },
            { id: 'm9t3', title: 'Roaming Hub Security' },
            { id: 'm9t4', title: 'Home-Routed vs Local Breakout Security' },
            { id: 'm9t5', title: 'Inter-PLMN Security Agreements' },
            { id: 'm9t6', title: 'Fraud Prevention in Roaming' },
        ],
    },
    {
        id: 'm10',
        title: 'Module 10: IoT and Massive MTC Security',
        topics: [
            { id: 'm10t1', title: 'Lightweight Security for IoT Devices' },
            { id: 'm10t2', title: 'Device Group Authentication' },
            { id: 'm10t3', title: 'NB-IoT and LTE-M Security' },
            { id: 'm10t4', title: 'Device Lifecycle Security Management' },
            { id: 'm10t5', title: 'Firmware Over-The-Air (FOTA) Security' },
            { id: 'm10t6', title: 'Zero-Touch Provisioning Security' },
        ],
    },
    {
        id: 'm11',
        title: 'Module 11: URLLC Security Challenges',
        topics: [
            { id: 'm11t1', title: 'Ultra-Reliable Low Latency Requirements' },
            { id: 'm11t2', title: 'Security vs Latency Trade-offs' },
            { id: 'm11t3', title: 'Mission-Critical Communication Security' },
            { id: 'm11t4', title: 'V2X (Vehicle-to-Everything) Security' },
            { id: 'm11t5', title: 'Industrial IoT (IIoT) Security' },
            { id: 'm11t6', title: 'Remote Surgery and Healthcare Security' },
        ],
    },
    {
        id: 'm12',
        title: 'Module 12: Threat Landscape and Attack Vectors',
        topics: [
            { id: 'm12t1', title: 'Signaling Storms and DoS Attacks' },
            { id: 'm12t2', title: 'Man-in-the-Middle (MITM) Attacks' },
            { id: 'm12t3', title: 'Rogue Base Station Attacks' },
            { id: 'm12t4', title: 'SIM Swapping and Cloning' },
            { id: 'm12t5', title: 'API Security Vulnerabilities' },
            { id: 'm12t6', title: 'Supply Chain Attacks on 5G Equipment' },
        ],
    },
    {
        id: 'm13',
        title: 'Module 13: AI/ML in 5G Security',
        topics: [
            { id: 'm13t1', title: 'AI-Powered Threat Detection' },
            { id: 'm13t2', title: 'Anomaly Detection in Network Traffic' },
            { id: 'm13t3', title: 'Machine Learning for Fraud Prevention' },
            { id: 'm13t4', title: 'Adversarial ML Attacks on 5G' },
            { id: 'm13t5', title: 'Automated Security Response Systems' },
            { id: 'm13t6', title: 'Security Analytics and SIEM Integration' },
        ],
    },
    {
        id: 'm14',
        title: 'Module 14: Security Testing and Penetration Testing',
        topics: [
            { id: 'm14t1', title: '5G Security Testing Methodologies' },
            { id: 'm14t2', title: 'Protocol Fuzzing for 5G Interfaces' },
            { id: 'm14t3', title: 'Vulnerability Assessment Tools' },
            { id: 'm14t4', title: 'Red Team vs Blue Team Exercises' },
            { id: 'm14t5', title: 'Security Auditing and Compliance' },
            { id: 'm14t6', title: 'Bug Bounty Programs for Telecom' },
        ],
    },
    {
        id: 'm15',
        title: 'Module 15: Regulatory and Compliance',
        topics: [
            { id: 'm15t1', title: 'GDPR and Data Protection in 5G' },
            { id: 'm15t2', title: 'Lawful Interception (LI) Requirements' },
            { id: 'm15t3', title: 'National Security Considerations' },
            { id: 'm15t4', title: 'Vendor Trust and Risk Assessment' },
            { id: 'm15t5', title: 'Critical Infrastructure Protection' },
            { id: 'm15t6', title: 'International Security Standards (NIST, ENISA)' },
        ],
    },
    {
        id: 'm16',
        title: 'Module 16: Private 5G and Enterprise Security',
        topics: [
            { id: 'm16t1', title: 'Private 5G Network Deployment Security' },
            { id: 'm16t2', title: 'Campus Network Security Architecture' },
            { id: 'm16t3', title: 'Integration with Enterprise Security' },
            { id: 'm16t4', title: 'CBRS and Shared Spectrum Security' },
            { id: 'm16t5', title: 'Hybrid Cloud Security for Private 5G' },
            { id: 'm16t6', title: 'Zero Trust Architecture in 5G' },
        ],
    },
    {
        id: 'm17',
        title: 'Module 17: Incident Response and Forensics',
        topics: [
            { id: 'm17t1', title: '5G Security Incident Response Framework' },
            { id: 'm17t2', title: 'Network Forensics in 5G' },
            { id: 'm17t3', title: 'Log Collection and Analysis' },
            { id: 'm17t4', title: 'Threat Intelligence Sharing' },
            { id: 'm17t5', title: 'Recovery and Business Continuity' },
            { id: 'm17t6', title: 'Post-Incident Analysis and Lessons Learned' },
        ],
    },
    {
        id: 'm18',
        title: 'Module 18: Future of 5G Security and 6G Preview',
        topics: [
            { id: 'm18t1', title: '5G-Advanced Security Enhancements' },
            { id: 'm18t2', title: 'Quantum-Safe Cryptography Timeline' },
            { id: 'm18t3', title: 'AI-Native Security in 6G' },
            { id: 'm18t4', title: 'Terahertz Communication Security' },
            { id: 'm18t5', title: 'Satellite-Terrestrial Integration Security' },
            { id: 'm18t6', title: 'Holographic Communication Security Challenges' },
        ],
    },
];

// Course metadata
export const COURSE_META = {
    title: '5G Security Masterclass',
    subtitle: 'Complete Professional Training with AI-Powered Learning',
    version: '2.0',
    totalModules: 18,
    totalTopics: 108,
    estimatedHours: 40,
    level: 'Advanced',
    certification: '5G Security Professional',
};
